version: '3.8'
services:
  backend:
    build: ../backend
    container_name: microtours-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app
    env_file:
      - ../backend/config/.env
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: microtours-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  # SQLite is file-based, no service needed for dev
